# Generated by Django 4.2.1 on 2023-06-26 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50)),
                ('num_people', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('picture_location', models.FileField(blank=True, null=True, upload_to='img/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ItemLocation',
            },
        ),
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('Private', 'private'), ('Public', 'public')], max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserP',
            },
        ),
        migrations.CreateModel(
            name='Renters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('id_Place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='places_app.itemlocation')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='places_app.userp')),
            ],
            options={
                'db_table': 'Renters',
            },
        ),
    ]
